apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boilerplate
  namespace: boilerplate
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: freecakes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: boilerplate
            port:
              number: 6041
