apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: boilerplate
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: api
        image: 767828748475.dkr.ecr.us-east-1.amazonaws.com/bolierplate:9
        imagePullPolicy: Always
        ports:
        - containerPort: 3500
