apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate
  namespace: boilerplate
  labels:
    role: boilerplate
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: boilerplate
  template:
    metadata:
      labels:
        role: boilerplate
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: boilerplate
        image: 767828748475.dkr.ecr.us-east-1.amazonaws.com/bolierplate:9
        imagePullPolicy: Always
        ports:
        - containerPort: 6041
